export const properties = [
  {
    propertyID: "311134",
    organizationID: "311686",
    propertyName: "Azzurro Boutique Hotel Surry Hills",
    pageLink: "/surry-hills",
    propertyImage:
      "https://h-img2.cloudbeds.com/uploads/311134/3_gallery~~65cdea3ab275e.jpeg",
    propertyDescription:
      "<div>Welcome to Sydney's first all-female hostel. Our team is dedicated to bringing fresh ideas to life, ensuring your stay is comfortable and homely.&nbsp;<br></div>We prioritize quality, offering delicious breakfast and dinner with daily cleaning services included in your stay. Whether you're travelling solo or with a group, we've created a welcoming space for you in Sydney. Understanding the challenges of settling into a new city, we aim to provide something different from the usual hotel experience.<br>We hope you enjoy our freshly prepared, home-cooked meals, and feel the comfort of a home away from home. We look forward to making your stay in Sydney enjoyable and comfortable.",
    propertyTimezone: "Australia/Sydney",
    propertyCurrency: {
      currencyCode: "AUD",
      currencySymbol: "$",
      currencyPosition: "before",
    },
  },
  {
    propertyID: "311272",
    organizationID: "311686",
    propertyName: "Azzurro Pod Hotel Potts Point",
    pageLink: "/potts-point",
    propertyImage:
      "https://h-img1.cloudbeds.com/uploads/311272/whatsapp_image_2023-10-17_at_05.59.54_gallery~~65cdd91845120.jpeg",
    propertyDescription:
      "<span>Welcome to Azzurro Pod Hotels, where we blend innovation with hospitality. Our team is dedicated to bringing fresh ideas to life, ensuring your stay is comfortable and homely.&nbsp;<br>We prioritize quality, offering delicious breakfast and dinner with daily cleaning services included in your stay. Whether you're travelling solo or with a group, we've created a welcoming space for you in Sydney. Understanding the challenges of settling into a new city, we aim to provide something different from the usual hotel experience.<br>We hope you enjoy our freshly prepared, home-cooked meals, and feel the comfort of a home away from home. We look forward to making your stay in Sydney enjoyable and comfortable.</span>",
    propertyTimezone: "Australia/Sydney",
    propertyCurrency: {
      currencyCode: "AUD",
      currencySymbol: "$",
      currencyPosition: "before",
    },
  },
  {
    propertyID: "317399",
    organizationID: "317399",
    propertyName: "Lisa demo account",
    pageLink: "/demo-property",
    propertyImage:
      "https://h-img2.cloudbeds.com/uploads/311134/3_gallery~~65cdea3ab275e.jpeg",
    propertyDescription: "",
    propertyTimezone: "America/Los_Angeles",
    propertyCurrency: {
      currencyCode: "USD",
      currencySymbol: "$",
      currencyPosition: "before",
    },
  },
];

export const getPropertiesMap = (): Record<string, any> => {
  return properties.reduce((acc: Record<string, any>, property) => {
    acc[property.propertyID] = property;
    return acc;
  }, {});
};

export const roomTypes = [
  {
    roomTypeID: "609900",
    propertyID: "311134",
    roomTypeName: "Private Room w/Shared Bathroom (4 ppl max)",
    roomTypeNameShort: "4 B",
    roomTypeDescription:
      "<span>A Mixed Private Room&nbsp;with a shared bathroom (max 4 people)<br><br><ul><li>Shared Bathroom available on each floor&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>Wardrobe &amp; Locker available for storage </li></ul></span>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img3.cloudbeds.com/uploads/311134/sh_4_beds_1~~65d6a9cfd3782.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/sh_4_beds_2~~65d6a9d87c9e6.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/sh_4_beds_3~~65d6a9d8ac991.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/sh_4_beds_4~~65d6a9d9d652f.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 4,
  },
  {
    roomTypeID: "613254",
    propertyID: "311134",
    roomTypeName: "TEST",
    roomTypeNameShort: "MIX",
    roomTypeDescription: "TEST ROOM",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [],
    roomTypeFeatures: [],
    roomsAvailable: 0,
    roomTypeUnits: 13,
  },
  {
    roomTypeID: "637220",
    propertyID: "311134",
    roomTypeName: "Double bedroom with private bathroom",
    roomTypeNameShort: "PRI",
    roomTypeDescription: "A Double bedroom with a private bathroom",
    isPrivate: true,
    maxGuests: 2,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img1.cloudbeds.com/uploads/311134/s1~~67fc7f77c07b4.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s4~~67fc7f8ee8717.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s3~~67fc7f8f0c208.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s2~~67fc7f914128f.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s1~~67fc7f9197760.jpg",
    ],
    roomTypeFeatures: ["220-240 volt circuits", "Wireless internet (WiFi)"],
    roomsAvailable: 0,
    roomTypeUnits: 4,
  },
  {
    roomTypeID: "645130",
    propertyID: "311134",
    roomTypeName: "Private Room for 2 Beds Shared",
    roomTypeNameShort: "BAL",
    roomTypeDescription: "Private Room for 2 Beds Shared",
    isPrivate: true,
    maxGuests: 2,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img3.cloudbeds.com/uploads/311134/s1~~67fc808e38feb.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s4~~67fc809e31e4c.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s3~~67fc809e4f25c.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s2~~67fc809ff0af6.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s1~~67fc80a03c5e2.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 5,
  },
  {
    roomTypeID: "645131",
    propertyID: "311134",
    roomTypeName: "MIXED 6 Beds Ensuite Bathroom",
    roomTypeNameShort: "MIX",
    roomTypeDescription:
      "A Mixed Room shared by 6 people with a private bathroom inside the room<br>&nbsp;<ul><li>Private Bathroom available inside the room&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>A mini-fridge available inside the room</li><li>Wardrobe &amp; Locker available for storage&nbsp;</li></ul>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img1.cloudbeds.com/uploads/311134/3_1~~68a8226bf3ea9.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/mixed_6_beds_ensuite~~68a8228a10b9e.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s3~~67fc84e67a788.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s2~~67fc84e84108c.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/download~~67fc84e982d58.png",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels ",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 6,
  },
  {
    roomTypeID: "645133",
    propertyID: "311134",
    roomTypeName: "MIXED 4 Beds Shared Bathroom",
    roomTypeNameShort: "MIX",
    roomTypeDescription:
      "A Mixed Room shared by 4 people with a shared bathroom<br><br><ul><li>Shared Bathroom available on each floor&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>Wardrobe &amp; Locker available for storage</li></ul>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img2.cloudbeds.com/uploads/311134/s1~~67fc822fa3efb.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s4~~67fc823a3ca93.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s3~~67fc823a6f680.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s2~~67fc823c0b021.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s1~~67fc823c52d3d.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 16,
  },
  {
    roomTypeID: "645139",
    propertyID: "311134",
    roomTypeName: "MIXED 4 Beds Ensuite Bathroom",
    roomTypeNameShort: "MIX",
    roomTypeDescription:
      "A Mixed Room shared by 4 people with a private bathroom inside the room<br>&nbsp;<ul><li>Private Bathroom available inside the room&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>Wardrobe &amp; Locker available for storage&nbsp;</li></ul>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img1.cloudbeds.com/uploads/311134/s2~~67fc81cc7cdc1.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s4~~67fc81d9e69a0.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s3~~67fc81d9c8e91.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s2~~67fc81db9383b.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s1~~67fc81dc61c11.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 4,
  },
  {
    roomTypeID: "645760",
    propertyID: "311134",
    roomTypeName: "Private Room w/ balcony & shared bathroom",
    roomTypeNameShort: "PBS",
    roomTypeDescription:
      "A private room with a balcony shared by 2 people with a shared bathroom<ul><li>Shared Bathroom available on each floor&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>A mini-fridge available inside the room</li><li>Wardrobe &amp; Locker available for storage</li></ul>",
    isPrivate: true,
    maxGuests: 2,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img2.cloudbeds.com/uploads/311134/s1~~67fc8156eb745.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s4~~67fc8164396a9.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s3~~67fc81642b208.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s2~~67fc8165d62bc.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s1~~67fc81662cf4d.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "4": "Air-conditioning",
      "1": "Extra Blankets ",
      "2": "Padlocks",
      "0": "Towels",
    },
    roomsAvailable: 0,
    roomTypeUnits: 3,
  },
  {
    roomTypeID: "646898",
    propertyID: "311134",
    roomTypeName: "Mixed 2 Beds Shared",
    roomTypeNameShort: "MIX",
    roomTypeDescription:
      "A Mixed Room shared by 2 people with a shared bathroom<br><br><ul><li>Shared Bathroom available on each floor&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price&nbsp;</li><li>A mini-fridge available inside the room</li><li>Wardrobe &amp; Locker available for storage&nbsp;</li></ul>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img3.cloudbeds.com/uploads/311134/s1~~67fc80136daa8.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s4~~67fc802004a6d.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s3~~67fc801fe22bf.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s2~~67fc8021e26a3.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s1~~67fc802238e9e.jpg",
    ],
    roomTypeFeatures: {
      "4": "110-120 volt circuits",
      "3": "Air-conditioning",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels",
    },
    roomsAvailable: 0,
    roomTypeUnits: 10,
  },
  {
    roomTypeID: "646899",
    propertyID: "311134",
    roomTypeName: "Mixed 2 Beds with Balcony (Shared Bathroom)",
    roomTypeNameShort: "MIZ",
    roomTypeDescription:
      "A Mixed Room with a balcony shared by 2 people with a shared bathroom<br><br><ul><li>Shared Bathroom available on each floor&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>A mini-fridge available inside the room</li><li>Wardrobe &amp; Locker available for storage&nbsp;</li></ul>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img1.cloudbeds.com/uploads/311134/s1~~67fc8101e542b.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/s4~~67fc811336edc.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/s3~~67fc81131ac48.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s2~~67fc8115121c5.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/s1~~67fc81153b7f2.jpg",
    ],
    roomTypeFeatures: {
      "4": "110-120 volt circuits",
      "3": "Air-conditioning",
      "1": "Extra Blankets ",
      "2": "Padlock",
      "0": "Towels",
    },
    roomsAvailable: 0,
    roomTypeUnits: 6,
  },
  {
    roomTypeID: "609890",
    propertyID: "311134",
    roomTypeName: "4 Beds Ensuite Bathroom (Female Only)",
    roomTypeNameShort: "4 B",
    roomTypeDescription:
      "<span>A Female only Room shared by 4 people with a private bathroom inside the room<br>&nbsp;<ul><li>Private Bathroom available inside the room&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li><span>Wardrobe &amp; Locker available for storage&nbsp;</span></li></ul></span>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img2.cloudbeds.com/uploads/311134/sh_4_beds_3~~65d6aa15542ec.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/sh_4beds_ensuite_1~~65d6aa2b918d0.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/sh_4beds_ensuite~~65d6aa2bc979a.jpg",
      "https://h-img3.cloudbeds.com/uploads/311134/sh_4beds_ensuite3~~65d6aa2ce672b.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/sh_4beds_ensuite4~~65d6aa2d67bb9.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets ",
      "2": "Padlocks",
      "0": "Towels",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 24,
  },
  {
    roomTypeID: "609891",
    propertyID: "311134",
    roomTypeName: "6 Beds Ensuite Bathroom (Female Only)",
    roomTypeNameShort: "6 B",
    roomTypeDescription:
      "<span>A Female only Room shared by 6 people with a private bathroom inside the room<br>&nbsp;<ul><li>Private Bathroom available inside the room&nbsp;</li><li>Complimentary Breakfast &amp; Dinner included in price</li><li>A mini-fridge available inside the room</li><li><span>Wardrobe &amp; Locker available for storage&nbsp;</span></li></ul></span>",
    isPrivate: false,
    maxGuests: 1,
    adultsIncluded: 1,
    childrenIncluded: 0,
    roomTypePhotos: [
      "https://h-img2.cloudbeds.com/uploads/311134/sh_6beds_ensuite_2~~65d6aa6780442.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/sh_6_beds_ensuite1~~65d6aa726b818.jpg",
      "https://h-img2.cloudbeds.com/uploads/311134/sh_6beds_ensuite_2~~65d6aa72870f2.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/sh_6beds_ensuite_3~~65d6aa73e78c2.jpg",
      "https://h-img1.cloudbeds.com/uploads/311134/sh_6beds_ensuite_4~~65d6aa74108e0.jpg",
    ],
    roomTypeFeatures: {
      "3": "110-120 volt circuits",
      "1": "Extra Blankets",
      "2": "Padlocks",
      "0": "Towels",
      "4": "Wireless internet (WiFi)",
    },
    roomsAvailable: 0,
    roomTypeUnits: 6,
  },
];

export const roomTypeCategories: { [key: string]: any } = {
  "Private Room for 6 People": {
    roomType: "Private Room for 6 People",
    numberOfRooms: 5.0,
    category: "Family Retreat",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Private Room for 4 People": {
    roomType: "Private Room for 4 People",
    numberOfRooms: 6.0,
    category: "Couple's Getaway",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed 4 Beds Ensuite": {
    roomType: "Mixed 4 Beds Ensuite",
    numberOfRooms: 1.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: "Most Popular",
  },
  "Mixed 6 Beds Ensuite": {
    roomType: "Mixed 6 Beds Ensuite",
    numberOfRooms: 3.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed 8 Beds Ensuite ": {
    roomType: "Mixed 8 Beds Ensuite ",
    numberOfRooms: 1.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: "Best Values",
  },
  "Female Pod Ensuite Bathroom - 8 people+ Bedroom": {
    roomType: "Female Pod Ensuite Bathroom - 8 people+ Bedroom",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: "Female only",
  },
  "Mixed Pod Ensuite - Large Room": {
    roomType: "Mixed Pod Ensuite - Large Room",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: "Budget Option",
  },
  "Mixed Pod 4 Beds Shared": {
    roomType: "Mixed Pod 4 Beds Shared",
    numberOfRooms: 6.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed Pod 6 Beds Shared": {
    roomType: "Mixed Pod 6 Beds Shared",
    numberOfRooms: 14.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed Pod 8 Beds Shared": {
    roomType: "Mixed Pod 8 Beds Shared",
    numberOfRooms: 2.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: null,
  },
  "Family Room ": {
    roomType: "Family Room ",
    numberOfRooms: 2.0,
    category: "Family Retreat",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Private Room for 8 people": {
    roomType: "Private Room for 8 people",
    numberOfRooms: 1.0,
    category: "Family Retreat",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed Pod Twin with Ensuite Bathroom": {
    roomType: "Mixed Pod Twin with Ensuite Bathroom",
    numberOfRooms: 1.0,
    category: "Couple's Getaway",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed Pod Twin with Shared Bathroom": {
    roomType: "Mixed Pod Twin with Shared Bathroom",
    numberOfRooms: 2.0,
    category: "Couple's Getaway",
    showOnHomepage: false,
    featuredValue: "Most Popular",
  },
  "Private Room (2 beds shared)": {
    roomType: "Private Room (2 beds shared)",
    numberOfRooms: 2.0,
    category: "Couple's Getaway",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Private Room (4 beds shared)": {
    roomType: "Private Room (4 beds shared)",
    numberOfRooms: 2.0,
    category: "Family Retreat",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed Pod 4 People Bedroom - Ensuite Bathroom": {
    roomType: "Mixed Pod 4 People Bedroom - Ensuite Bathroom",
    numberOfRooms: 1.0,
    category: "Family Retreat",
    showOnHomepage: false,
    featuredValue: null,
  },
  "Female only Pod 6 Beds Room-Ensuite": {
    roomType: "Female only Pod 6 Beds Room-Ensuite",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: "Female only",
  },
  "Mixed Pod 4 Beds Room with Shared Bathroom": {
    roomType: "Mixed Pod 4 Beds Room with Shared Bathroom",
    numberOfRooms: 2.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Mixed Pod 6 Beds Room with Shared Bathroom": {
    roomType: "Mixed Pod 6 Beds Room with Shared Bathroom",
    numberOfRooms: 3.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: "Best Values",
  },
  "Loss Leader - Mixed Pod 8 Shared Bathroom": {
    roomType: "Loss Leader - Mixed Pod 8 Shared Bathroom",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: "Budget Option",
  },
  "Double bedroom with private bathroom": {
    roomType: "Double bedroom with private bathroom",
    numberOfRooms: 4.0,
    category: "Couple's Getaway",
    showOnHomepage: true,
    featuredValue: "Most Popular",
  },
  "Mixed 2 Beds Shared Bathroom": {
    roomType: "Mixed 2 Beds Shared Bathroom",
    numberOfRooms: 5.0,
    category: "Luxury stay",
    showOnHomepage: false,
    featuredValue: null,
  },
  "Mixed 2 Beds with Balcony (Shared Bathroom)": {
    roomType: "Mixed 2 Beds with Balcony (Shared Bathroom)",
    numberOfRooms: 3.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Private Room for 2 Beds Shared": {
    roomType: "Private Room for 2 Beds Shared",
    numberOfRooms: 5.0,
    category: "Couple's Getaway",
    showOnHomepage: true,
    featuredValue: null,
  },
  "Private Room w/ balcony & shared bathroom": {
    roomType: "Private Room w/ balcony & shared bathroom",
    numberOfRooms: 3.0,
    category: "Couple's Getaway",
    showOnHomepage: false,
    featuredValue: null,
  },
  "Private Room w/Shared Bathroom (4 ppl max)": {
    roomType: "Private Room w/Shared Bathroom (4 ppl max)",
    numberOfRooms: 4.0,
    category: "Family Retreat",
    showOnHomepage: true,
    featuredValue: null,
  },
  "4 Beds Ensuite Bathroom (Female Only)": {
    roomType: "4 Beds Ensuite Bathroom (Female Only)",
    numberOfRooms: 6.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: "Female only",
  },
  "6 Beds Ensuite Bathroom (Female Only)": {
    roomType: "6 Beds Ensuite Bathroom (Female Only)",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: null,
  },
  "MIXED 4 Beds Ensuite Bathroom": {
    roomType: "MIXED 4 Beds Ensuite Bathroom",
    numberOfRooms: 1.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: "Best Values",
  },
  "MIXED 6 Beds Ensuite Bathroom": {
    roomType: "MIXED 6 Beds Ensuite Bathroom",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: "Budget Option",
  },
  "MIXED 4 Beds Shared Bathroom": {
    roomType: "MIXED 4 Beds Shared Bathroom",
    numberOfRooms: 4.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: null,
  },
  "SINGLE BEDROOM WITH HARBOUR VIEW": {
    roomType: "SINGLE BEDROOM WITH HARBOUR VIEW",
    numberOfRooms: 1.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: "Most Popular",
  },
  "MIXED POD TWIN ROOM WITH HARBOUR VIEW": {
    roomType: "MIXED POD TWIN ROOM WITH HARBOUR VIEW",
    numberOfRooms: 1.0,
    category: "Luxury stay",
    showOnHomepage: true,
    featuredValue: null,
  },
  "MIXED POD TWIN ROOM": {
    roomType: "MIXED POD TWIN ROOM",
    numberOfRooms: 5.0,
    category: "Luxury stay",
    showOnHomepage: false,
    featuredValue: null,
  },
  "Mixed Pod 4 Beds Room with Harbour Bridge View": {
    roomType: "Mixed Pod 4 Beds Room with Harbour Bridge View",
    numberOfRooms: 7.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: "Best Values",
  },
  "PRIVATE Bunk Bed Room (max 4)": {
    roomType: "PRIVATE Bunk Bed Room (max 4)",
    numberOfRooms: 7.0,
    category: "Family Retreat",
    showOnHomepage: true,
    featuredValue: null,
  },
  "MIXED POD ROOM - 4 people bedroom": {
    roomType: "MIXED POD ROOM - 4 people bedroom",
    numberOfRooms: 6.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: null,
  },
  "MIXED POD ROOM - 6 people bedroom": {
    roomType: "MIXED POD ROOM - 6 people bedroom",
    numberOfRooms: 3.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: null,
  },
  "FEMALE ONLY Pod Room 6 people bedroom": {
    roomType: "FEMALE ONLY Pod Room 6 people bedroom",
    numberOfRooms: 3.0,
    category: "Solo Explorer",
    showOnHomepage: false,
    featuredValue: "Female only",
  },
  "Lost Leader - Mixed Pod Room 8 people bedroom": {
    roomType: "Lost Leader - Mixed Pod Room 8 people bedroom",
    numberOfRooms: 1.0,
    category: "Solo Explorer",
    showOnHomepage: true,
    featuredValue: "Budget Option",
  },
};
